#Locate
export LANG=ja_JP.UTF-8
export LC_ALL=ja_JP.UTF-8

#Path
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"

alias emacs="/usr/local/bin/emacs -nw"
alias emacsclient="/usr/local/bin/emacsclient"

alias e="emacsclient -n $* || open -a /Applications/Emacs.app $*"
alias EDITOR="emacsclient -t"

#python
export PYTHONPATH=/usr/local/lib/python2.7/site-packages/

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# rake
alias rake="noglob rake"

