* Shin's Emacs Configuration
** Install
** Description
*** Contents
[[http://www.clear-code.com/blog/2011/2/16.html][ココ]]を参考にして以下のようなフォルダ構成にしている。
# tree の結果
#+BEGIN_SRC text
├── .emacs.d
│   ├── config              
│   │   ├── builtins.el    ← 標準elispの設定
│   │   ├── local.el       ← 環境に依存する設定(バージョン管理外)
│   │   ├── el-get         ← el-get の設定（レシピなど）
│   │   ├── packages       ← 非標準elispの設定
│   │   └── packages.el    ← 標準elispの設定
│   ├── el-get             ← el-getでインストールしたelispファイル
│   ├── elpa               ← package.elでインストールしたelispファイル
│   ├── init.el            ← 基本的な設定
│   ├── initfunc.el        ← Macro(auto-async-byte-complie設定用)
│   └── var                ← 一時ファイル置き場
│       ├── auto-complete
│       ├── savehist
│       └── session
├── .gitignore
└── README.org             ← このファイル

#+END_SRC


**** 利用している非標準ELISP
- auto-complete
- color-moccur
- cp5022x
- cygwin-mount
- dmacro
- gtags
- helm
- lua-mode
- magit
- markdown-mode
- migemo
- popwin
- sdic
- setup-cygwin
- session
- sr-speedbar
- tabbar
- text-translator
- yasnippet

 
**** 利用しなくなった非標準ELISP
- apel
- anything
- auto-install
- calfw
- color-theme
- elscreen
- htmlize.el
- japanese-holidays.el
- mcomplete.el
- minibuf-isearch.el
- mozc.el

** Tips
起動していないときは open -a を使って、Emacs の起動、起動しているときは emacsclient で既存の Emacs でファイルを開くということをしたい。
また、Mac OSX で alfred を利用して Emacs を起動したい。
そのようなときは automator を使って、次のようなシェルを実行して app 化すればいい。
入力の引き渡し方法は「引数として」を選択している。

#+BEGIN_SRC sh
EMACS_CLIENT=/usr/local/bin/emacsclient
if [ $# -ne 1 ]; then
  open -a Emacs
  exit 0
fi

for f in "$@"
do
   $EMACS_CLIENT --alternate-editor=“” -n "$f"
done
#+END_SRC

emacsclient の alternateeditor オプションで open -a を実行できなかったので、以下のような方針で実行している。
  - 引数無しのときは Emacs を起動
  - 引数有りのときは emacsclient の実行
Emacs 未起動時に引数有りの emacsclient を実行されるとエラーとなるが、そうなったら alfred で起動してやればいい。
Applescript を組んで Emacs 未起動時は "open -a" 、起動時は emacsclient を実行すればいいとは思うのだが、手抜きをしている。

